// Autogenerated file, do not edit!
#include "torch_ipex/csrc/version.h"

namespace torch_ipex {

const char IPEX_GITREV[] = {"6e1404c165151b4463f6f45b39924749975a73cf"};
const char TORCH_GITREV[] = {""};

}  // namespace torch_ipex
