// Autogenerated file by ${command}. Do not edit directly!
#include <ATen/${Type}.h>

#include <ATen/Context.h>
#include <torch/library.h>

namespace at {

namespace ${Type}_impl {

${type_derived_method_definitions}

}  // namespace ${Type}_impl

namespace ${Type} {


TORCH_LIBRARY_IMPL(aten, ${Backend}, m) {
${wrapper_registrations}
}

}  // namespace ${Type}

} // namespace at
