// Autogenerated file by ${command}. Do not edit directly!
#pragma once

#include <ATen/Tensor.h>
#include <ATen/ipex_type_dpcpp_customized.h>

namespace at {

namespace ${Type} {

  void RegisterAtenTypeFunctions();

  ${type_derived_method_declarations}
}

} // namespace at
