// Autogenerated file by gen-common-ops.py. Do not edit directly!
#pragma once

#include <ATen/ATen.h>
#include <vector>

namespace torch_ipex {

class AtenIpexTypeMLPExt {
 public:
  static at::Tensor forward(void *handle_, const at::Tensor &input, const at::Tensor &weight, const at::Tensor &bias);
  static std::vector<at::Tensor> backward(void *handle_, const at::Tensor &grad_output, const at::Tensor &input, const at::Tensor &weight);
  static void *create_handle(int N, int C, int K, int bn, int bc, int bk, int dtype, int fuse_bias, int act_type);
  static at::Tensor set_relu_mask(void *handle_);
  static void release_handle(void* handle_);
};

}  // namespace torch_ipex
