// Autogenerated file by gen.py. Do not edit directly!

#include <ATen/Tensor.h>

namespace at {

class AtenIpexTypeDefault {
 public:
  static at::Tensor add(const at::Tensor & self, const at::Tensor & other, at::Scalar alpha);

};

void RegisterAtenTypeFunctions();

}  // namespace at

