// Autogenerated file, do not edit!
#include "torch_dpcpp/csrc/version.h"

namespace torch_ipex {

const char IPEX_GITREV[] = {"93d80403edfa8ea11ad07b81a3169f2e029d5850"};
const char TORCH_GITREV[] = {""};

}  // namespace torch_ipex
