// Autogenerated file, do not edit!
#include "torch_dpcpp/csrc/version.h"

namespace torch_ipex {

const char IPEX_GITREV[] = {"ac2f7456bbeb63fb396b053675611637d2ae4293"};
const char TORCH_GITREV[] = {""};

}  // namespace torch_ipex
