## Included by CMakeLists
if(Options_GPU_cmake_included)
    return()
endif()
set(Options_GPU_cmake_included true)

# The options to build ipex gpu
include(CMakeDependentOption)
option(USE_ONEMKL "Use oneMKL BLAS" ON)
option(USE_CHANNELS_LAST_1D "Use channels last 1d" ON)
option(USE_PERSIST_STREAM "Use persistent oneDNN stream" ON)
option(USE_SCRATCHPAD_MODE "Use oneDNN scratchpad mode" ON)
option(USE_PRIMITIVE_CACHE "Cache oneDNN primitives by FRAMEWORK, instead of oneDNN itself" OFF)
option(USE_QUEUE_BARRIER "Use queue submit_barrier, otherwise use dummy kernel" ON)
option(USE_MULTI_CONTEXT "Create DPC++ runtime context per device" ON)
option(BUILD_STATS "Count statistics for each component during build process" OFF)
option(BUILD_WITH_XPU "Build XPU backend implementation" ON)
option(BUILD_BY_PER_KERNEL "Build by DPC++ per_kernel option (exclusive with USE_AOT_DEVLIST)" OFF)
option(BUILD_STRIPPED_BIN "Strip all symbols after build" OFF)
option(BUILD_INTERNAL_DEBUG "Use internal debug code path" OFF)
option(BUILD_NO_CLANGFORMAT "Build without force clang-format" OFF)
option(BUILD_SEPARATE_OPS "Build each operator in separate library" OFF)
set(USE_AOT_DEVLIST "" CACHE STRING "Set device list for AOT build (for example, skl,ats,...)")
option(USE_PROFILER "USE XPU Profiler in build." ON)
option(USE_SYCL_ASSERT "Enables assert in sycl kernel" OFF)
option(BUILD_SIMPLE_TRACE "Build simple trace for each registered operator" ON)
set(BUILD_OPT_LEVEL "" CACHE STRING "Add build option -Ox, accept values: 0/1")
option(BUILD_JIT_QUANTIZATION_SAVE "Support jit quantization model save and load" OFF)