# - Try to find oneDPL
#

IF (NOT ONEDPL_FOUND)
SET(ONEDPL_FOUND OFF)

SET(ONEDPL_LIBRARIES)
SET(ONEDPL_INCLUDE_DIR)

SET(ONEDPL_ROOT "${PROJECT_SOURCE_DIR}/third_party/oneDPL")

FIND_PATH(ONEDPL_INCLUDE_DIR oneapi/dpl/algorithm PATHS ${ONEDPL_ROOT} PATH_SUFFIXES include)

IF (NOT ONEDPL_INCLUDE_DIR)
  MESSAGE(STATUS "oneDPL headers not found!")
  RETURN()
ENDIF(NOT ONEDPL_INCLUDE_DIR)

add_library(oneDPL INTERFACE)
target_include_directories(oneDPL INTERFACE ${ONEDPL_INCLUDE_DIR})
SET(ONEDPL_FOUND ON)

ENDIF(NOT ONEDPL_FOUND)
